import { useState } from 'react';
import { useApp } from '../context/useApp';
import useResource from '../hooks/useResource';
import AccountNav from '../components/AccountNav';
import PageTitle from '../components/PageTitle';
import Loading from '../components/Loading';
import ErrorMessage from '../components/ErrorMessage';
import ConfirmDialog from '../components/ConfirmDialog';
import Icon from '../components/Icon';
import { idOf } from '../models/entities';
import { money } from '../utils/format';
const emptyGame = { titulo: '', descricao: '', generos: '', plataformas: 'PC', imagemCapa: '', linksReferencia: '' };
const emptyOffer = { jogoId: '', loja: '', preco: '', precoOriginal: '', urlLoja: '' };
const list = text => text.split(',').map(t => t.trim()).filter(Boolean);
function Manager({ data, tab, setTab }) {
  const { api, user, notify, refresh } = useApp(); const [gameId, setGameId] = useState(''); const [offerId, setOfferId] = useState(''); const [gameForm, setGameForm] = useState(emptyGame); const [offerForm, setOfferForm] = useState(emptyOffer); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [remove, setRemove] = useState(null);
  const setGame = e => setGameForm(f => ({ ...f, [e.target.name]: e.target.value })); const setOffer = e => setOfferForm(f => ({ ...f, [e.target.name]: e.target.value }));
  function editGame(g) { setGameId(g.id); setGameForm({ ...g, generos: g.generos.join(', '), plataformas: g.plataformas.join(', '), linksReferencia: g.linksReferencia.join(', ') }); setTab('jogos'); setError(''); window.scrollTo({ top: 150, behavior: 'smooth' }); }
  function editOffer(o) { setOfferId(o.id); setOfferForm({ jogoId: idOf(o.jogo), loja: o.loja, preco: o.preco, precoOriginal: o.precoOriginal ?? '', urlLoja: o.urlLoja || '' }); setTab('ofertas'); setError(''); window.scrollTo({ top: 150, behavior: 'smooth' }); }
  async function submitGame(e) { e.preventDefault(); setBusy(true); setError(''); try { await api.saveGame(gameId || null, { titulo: gameForm.titulo.trim(), descricao: gameForm.descricao.trim(), generos: list(gameForm.generos), plataformas: list(gameForm.plataformas), imagemCapa: gameForm.imagemCapa.trim(), linksReferencia: list(gameForm.linksReferencia) }); notify(gameId ? 'Jogo atualizado!' : 'Jogo adicionado ao catálogo!'); setGameId(''); setGameForm(emptyGame); refresh(); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  async function submitOffer(e) { e.preventDefault(); setBusy(true); setError(''); try { await api.saveOffer(offerId || null, { ...(!offerId && { jogoId: offerForm.jogoId }), loja: offerForm.loja.trim(), preco: Number(offerForm.preco), precoOriginal: offerForm.precoOriginal === '' ? null : Number(offerForm.precoOriginal), urlLoja: offerForm.urlLoja.trim() }); notify(offerId ? 'Preço atualizado e registrado no histórico!' : 'Oferta adicionada!'); setOfferId(''); setOfferForm(emptyOffer); refresh(); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  async function deleteItem() { setBusy(true); try { await api[remove.kind === 'game' ? 'deleteGame' : 'deleteUser'](remove.id); setRemove(null); refresh(); notify('Registro excluído.'); } catch (err) { notify(err.message, 'error'); } finally { setBusy(false); } }
  return <><div className="detail-tabs" role="tablist" aria-label="Painel de administração">{[['jogos', 'Jogos do catálogo'], ['ofertas', 'Ofertas e preços'], ['usuarios', 'Usuários']].map(([key, title]) => <button key={key} role="tab" aria-selected={tab === key} className={tab === key ? 'active' : ''} onClick={() => { setTab(key); setError(''); }}>{title}</button>)}</div>
    {tab === 'jogos' && <><form className="panel form admin-form" onSubmit={submitGame}><div className="panel-heading"><h2>{gameId ? 'Editar jogo' : 'Adicionar jogo ao catálogo'}</h2>{gameId && <button type="button" className="link-button" onClick={() => { setGameId(''); setGameForm(emptyGame); }}>Cancelar edição</button>}</div><div className="form-row"><label>Título<input name="titulo" required maxLength="150" value={gameForm.titulo} onChange={setGame}/></label><label>URL da capa<input name="imagemCapa" value={gameForm.imagemCapa} onChange={setGame} placeholder="https://... ou /games/arquivo.jpg"/></label></div><div className="form-row"><label>Gêneros (separados por vírgula)<input name="generos" value={gameForm.generos} onChange={setGame} placeholder="RPG, Aventura"/></label><label>Plataformas (separadas por vírgula)<input name="plataformas" required value={gameForm.plataformas} onChange={setGame} placeholder="PC, PlayStation 5"/></label></div><label>Descrição<textarea name="descricao" rows="3" value={gameForm.descricao} onChange={setGame}/></label><label>Links de referência (separados por vírgula)<input name="linksReferencia" value={gameForm.linksReferencia} onChange={setGame} placeholder="https://store.steampowered.com/app/..."/></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="btn primary" disabled={busy}>{busy ? 'Salvando…' : gameId ? 'Salvar jogo' : 'Adicionar jogo'}<Icon name="plus" size={16}/></button></form><div className="panel section table-wrap"><table><thead><tr><th>Jogo</th><th>Plataformas</th><th>Ações</th></tr></thead><tbody>{data.games.map(g => <tr key={g.id}><td>{g.titulo}</td><td>{g.plataformas.join(', ')}</td><td><div className="table-actions"><button className="link-button" onClick={() => editGame(g)}>Editar</button><button className="icon-btn danger-text" aria-label={`Excluir jogo ${g.titulo}`} onClick={() => setRemove({ id: g.id, kind: 'game', name: g.titulo })}><Icon name="trash" size={16}/></button></div></td></tr>)}</tbody></table></div></>}
    {tab === 'ofertas' && <><form className="panel form admin-form" onSubmit={submitOffer}><div className="panel-heading"><h2>{offerId ? 'Atualizar preço da oferta' : 'Cadastrar oferta'}</h2>{offerId && <button type="button" className="link-button" onClick={() => { setOfferId(''); setOfferForm(emptyOffer); }}>Cancelar edição</button>}</div><div className="form-row"><label>Jogo<select name="jogoId" required disabled={!!offerId} value={offerForm.jogoId} onChange={setOffer}><option value="">Selecione</option>{data.games.map(g => <option key={g.id} value={g.id}>{g.titulo}</option>)}</select></label><label>Loja<input name="loja" required maxLength="80" value={offerForm.loja} onChange={setOffer} placeholder="Steam, Nuuvem..."/></label></div><div className="form-row"><label>Preço atual (R$)<input name="preco" type="number" min="0" step="0.01" required value={offerForm.preco} onChange={setOffer}/></label><label>Preço original (R$, opcional)<input name="precoOriginal" type="number" min="0" step="0.01" value={offerForm.precoOriginal} onChange={setOffer}/></label></div><label>URL da oferta<input name="urlLoja" type="url" value={offerForm.urlLoja} onChange={setOffer} placeholder="https://..."/></label><p className="small-note">Cada atualização de preço cria um novo ponto no histórico. O desconto é calculado automaticamente.</p>{error && <p className="form-error" role="alert">{error}</p>}<button className="btn primary" disabled={busy}>{busy ? 'Salvando…' : offerId ? 'Atualizar preço' : 'Cadastrar oferta'}<Icon name="tag" size={16}/></button></form><div className="panel section table-wrap"><table><thead><tr><th>Jogo</th><th>Loja</th><th>Preço</th><th>Desconto</th><th>Ação</th></tr></thead><tbody>{data.offers.map(o => <tr key={o.id}><td>{o.jogo?.titulo || 'Jogo removido'}</td><td>{o.loja}</td><td>{money(o.preco)}</td><td>{o.discount}%</td><td><button className="link-button" onClick={() => editOffer(o)}>Atualizar</button></td></tr>)}</tbody></table></div></>}
    {tab === 'usuarios' && <div className="panel table-wrap"><div className="panel-heading"><h2>Usuários cadastrados</h2><span>{data.users.length} usuários</span></div><table><thead><tr><th>Nome</th><th>E-mail</th><th>Perfil</th><th>Ação</th></tr></thead><tbody>{data.users.map(u => <tr key={u.id}><td>{u.nome}</td><td>{u.email}</td><td>{u.perfil === 'admin' ? 'Administrador' : 'Jogador'}</td><td>{u.id === user.id ? <span className="muted">Sua conta</span> : <button className="icon-btn danger-text" aria-label={`Excluir usuário ${u.nome}`} onClick={() => setRemove({ id: u.id, kind: 'user', name: u.nome })}><Icon name="trash" size={16}/></button>}</td></tr>)}</tbody></table></div>}
    <ConfirmDialog open={!!remove} title={`Excluir ${remove?.kind === 'game' ? 'jogo' : 'usuário'}?`} text={`${remove?.name || ''} será removido. Registros com vínculos ativos não podem ser excluídos.`} busy={busy} onCancel={() => setRemove(null)} onConfirm={deleteItem}/>
  </>;
}
export default function Admin() { const [tab, setTab] = useState('jogos'); const { api } = useApp(); const { data, loading, error, reload } = useResource('admin', async () => { const [catalog, users] = await Promise.all([api.catalog(), api.users()]); return { ...catalog, users }; }); return <><PageTitle eyebrow="ADMINISTRAÇÃO" title="O próximo jogo começa no catálogo." text="Gerencie jogos, cadastre ofertas e mantenha os preços atualizados."/><AccountNav/>{loading ? <Loading/> : error ? <ErrorMessage message={error} onRetry={reload}/> : <Manager data={data} tab={tab} setTab={setTab}/>}</>; }
