import { useState } from 'react';
import { Link, Navigate, useNavigate, useSearchParams } from 'react-router-dom';
import { useApp } from '../context/useApp';
import { config } from '../services/config';
import Icon from '../components/Icon';
export default function Auth({ register = false }) {
  const { authenticate, user, notify } = useApp(); 
  const [params] = useSearchParams(); 
  const navigate = useNavigate();
  const [form, setForm] = useState({ nome: '', email: '', senha: '', confirm: '', dataNascimento: '' }); 
  const [busy, setBusy] = useState(false); 
  const [error, setError] = useState(''); 
  const [show, setShow] = useState(false);
  const target = params.get('redirect'); 
  const redirect = target?.startsWith('/') && !target.startsWith('//') && !target.startsWith('/entrar') && !target.startsWith('/cadastro') ? target : '/perfil';
  if (user) return <Navigate to={redirect} replace/>;
  const set = e => setForm(f => ({ ...f, [e.target.name]: e.target.value }));
  async function submit(e) { e.preventDefault(); setError(''); if (register && form.senha !== form.confirm) { setError('As senhas precisam ser iguais.'); return; } setBusy(true); try { let payload = register ? { nome: form.nome.trim(), email: form.email.trim().toLowerCase(), senha: form.senha } : { email: form.email.trim().toLowerCase(), senha: form.senha }; if (register && form.dataNascimento) payload.dataNascimento = form.dataNascimento; await authenticate(register ? 'register' : 'login', payload); notify(register ? 'Conta criada. Bem-vindo ao UniGames!' : 'Bom te ver por aqui!'); navigate(redirect, { replace: true }); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  async function demo() { setBusy(true); setError(''); try { await authenticate('login', { email: 'demo@unigames.com', senha: 'unigames123' }); navigate(redirect); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <section className="auth-layout"><div className="auth-art"><div className="auth-art-overlay"/><div className="auth-art-copy"><span className="brand"><Icon name="gamepad" size={32}/>uni<span>games</span><b>●</b></span><p className="eyebrow">SEU PRÓXIMO PLAY COMEÇA AQUI</p><h1>Todo grande jogo<br/>começa com<br/>uma escolha<span>.</span></h1><p>Salve seus favoritos, compare preços e faça parte de uma comunidade que joga junto.</p><div className="auth-art-footer"><Icon name="shield" size={19}/>Sua conta. Suas próximas aventuras.</div></div></div><div className="auth-form-wrap"><Link to="/" className="back-link">← Voltar para descobrir</Link><h2>{register ? 'Vamos começar?' : 'Bem-vindo de volta.'}</h2><p>{register ? 'Crie sua conta e descubra seu próximo jogo.' : 'Entre para continuar a sua jornada.'}</p><form onSubmit={submit} className="form">{register && <label>Seu nome<input name="nome" autoComplete="name" required maxLength="80" value={form.nome} onChange={set} placeholder="Como podemos te chamar?"/></label>}{register && <label>Data de Nascimento (Opcional)<input name="dataNascimento" type="date" value={form.dataNascimento} onChange={set} max={new Date().toISOString().split('T')[0]}/></label>}<label>E-mail<input name="email" type="email" autoComplete="email" required maxLength="150" value={form.email} onChange={set} placeholder="voce@exemplo.com"/></label><label>Senha<div className="password-field"><input name="senha" aria-label="Senha" type={show ? 'text' : 'password'} autoComplete={register ? 'new-password' : 'current-password'} required minLength={register ? 6 : undefined} maxLength="128" value={form.senha} onChange={set} placeholder={register ? 'Pelo menos 6 caracteres' : 'Sua senha'}/><button type="button" className="link-button" onClick={() => setShow(!show)}>{show ? 'Ocultar' : 'Mostrar'}</button></div></label>{register && <label>Confirmar senha<input name="confirm" type={show ? 'text' : 'password'} autoComplete="new-password" required value={form.confirm} onChange={set} placeholder="Repita sua senha"/></label>}{error && <p className="form-error" role="alert">{error}</p>}<button className="btn primary full" disabled={busy}>{busy ? 'Aguarde…' : register ? 'Criar minha conta' : 'Entrar na minha conta'}<Icon name="arrow" size={17}/></button></form>{config.source === 'demo' && <><div className="form-divider"><span>ou explore agora</span></div><button className="btn secondary full" onClick={demo} disabled={busy}><Icon name="gamepad" size={18}/>Usar conta de demonstração</button><p className="demo-auth-note">Esta versão usa dados locais para apresentação. As alterações de demonstração ficam neste navegador.</p></>}<p className="auth-switch">{register ? 'Já tem uma conta?' : 'Ainda não tem uma conta?'} <Link to={`${register ? '/entrar' : '/cadastro'}${target ? `?redirect=${encodeURIComponent(redirect)}` : ''}`}>{register ? 'Entrar' : 'Criar conta'}</Link></p></div></section>;
}
