import { useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useApp } from '../context/useApp';
import useResource from '../hooks/useResource';
import PageTitle from '../components/PageTitle';
import GameImage from '../components/GameImage';
import Loading from '../components/Loading';
import ErrorMessage from '../components/ErrorMessage';
import EmptyState from '../components/EmptyState';
import Icon from '../components/Icon';
import { idOf } from '../models/entities';
import { money } from '../utils/format';
function Editor({ data, id }) {
  const { api, user, notify, refresh } = useApp(); const navigate = useNavigate(); const original = data.listing;
  const [form, setForm] = useState({ jogoId: idOf(original?.jogo) || '', preco: original?.preco ?? '', estadoConservacao: original?.estadoConservacao || 'Excelente', plataforma: original?.plataforma || '', descricao: original?.descricao || '', nome: original?.contato.nome || user.nome, info: original?.contato.info || user.email, status: original?.status || 'ativo' });
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const game = data.games.find(g => g.id === form.jogoId);
  if (id && idOf(original.vendedor) !== user.id && user.perfil !== 'admin') return <EmptyState icon="shield" title="Este anúncio pertence a outro jogador" text="Você pode editar os anúncios publicados pela sua conta."/>;
  const set = e => setForm(f => ({ ...f, [e.target.name]: e.target.value }));
  async function submit(e) { e.preventDefault(); if (!Number.isFinite(Number(form.preco)) || Number(form.preco) < 0) { setError('Informe um preço válido.'); return; } setBusy(true); setError(''); const input = { preco: Number(form.preco), estadoConservacao: form.estadoConservacao, plataforma: form.plataforma, contato: { nome: form.nome.trim(), info: form.info.trim() }, descricao: form.descricao.trim(), ...(id ? { status: form.status } : { jogoId: form.jogoId }) }; try { await api.saveListing(id, input); notify(id ? 'Anúncio atualizado!' : 'Seu anúncio já está na comunidade!'); refresh(); navigate('/meus-anuncios'); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <><Link to="/meus-anuncios" className="back-link">← Voltar para meus anúncios</Link><PageTitle eyebrow="UM NOVO DESTINO PARA SUA COLEÇÃO" title={id ? 'Editar anúncio' : 'Anuncie seu jogo físico'} text="Conte um pouco sobre o jogo e facilite a próxima aventura de alguém."/><div className="listing-form-layout"><form className="panel form" onSubmit={submit}><h2>Informações do jogo</h2><label>Jogo do catálogo<select name="jogoId" required disabled={!!id} value={form.jogoId} onChange={e => { set(e); setForm(f => ({ ...f, plataforma: '' })); }}><option value="">Selecione um jogo</option>{data.games.map(g => <option key={g.id} value={g.id}>{g.titulo}</option>)}</select></label><div className="form-row"><label>Plataforma da mídia<select name="plataforma" required value={form.plataforma} onChange={set}><option value="">Selecione</option>{(game?.plataformas.filter(p => p !== 'PC') || []).map(p => <option key={p}>{p}</option>)}</select></label><label>Conservação<select name="estadoConservacao" value={form.estadoConservacao} onChange={set}>{['Novo', 'Excelente', 'Bom', 'Marcas de Uso'].map(p => <option key={p}>{p}</option>)}</select></label></div><label>Preço (R$)<input name="preco" type="number" min="0" max="999999" step="0.01" required value={form.preco} onChange={set} placeholder="0,00"/></label><label>Descrição<textarea name="descricao" rows="4" maxLength="2000" value={form.descricao} onChange={set} placeholder="Tem caixa original? Como está o disco? Onde pode entregar?"/></label>{id && <label>Status<select name="status" value={form.status} onChange={set}><option value="ativo">Disponível</option><option value="pausado">Pausado</option><option value="vendido">Vendido</option></select></label>}<hr/><h2>Como falar com você</h2><div className="form-row"><label>Nome no anúncio<input name="nome" required maxLength="80" value={form.nome} onChange={set}/></label><label>E-mail ou telefone<input name="info" required maxLength="150" value={form.info} onChange={set}/></label></div><p className="small-note">Seu contato aparecerá no anúncio para que os interessados falem diretamente com você.</p>{error && <p className="form-error" role="alert">{error}</p>}<div className="form-actions"><Link to="/meus-anuncios" className="btn secondary">Cancelar</Link><button className="btn primary" disabled={busy || !data.games.length}>{busy ? 'Salvando…' : id ? 'Salvar alterações' : 'Publicar anúncio'}<Icon name="arrow" size={17}/></button></div></form><aside><div className="panel listing-preview"><p className="eyebrow accent">PRÉVIA DO SEU ANÚNCIO</p><GameImage game={game}/><h2>{game?.titulo || 'Seu próximo anúncio'}</h2><p>{form.plataforma || 'Plataforma'} · {form.estadoConservacao}</p><strong className="listing-big-price">{money(form.preco)}</strong><hr/><p><Icon name="shield" size={17}/>Descreva o estado real da mídia. Uma boa descrição ajuda todo mundo a fazer uma boa escolha.</p></div></aside></div></>;
}
export default function FormAnuncio() {
  const { id } = useParams(); const { api } = useApp(); const { data, loading, error, reload } = useResource(`listing-form:${id || 'new'}`, async () => { const [catalog, listing] = await Promise.all([api.catalog(), id ? api.listing(id) : Promise.resolve(null)]); return { ...catalog, listing }; });
  if (loading) return <Loading/>; if (error) return <ErrorMessage message={error} onRetry={reload}/>;
  return <Editor key={id || 'new'} data={data} id={id}/>;
}
